In [3]:
"""Numpy is a fundamental library for sciencitific computing in Python.It provides support 
for arrays and matrices , along with a collection of mathematical functions to operate on these data structures.
In thos lesson, we will cover the basics of Numpy , focusing on arrays and vectorized operations."""

'Numpy is a fundamental library for sciencitific computing in Python.It provides support \nfor arrays and matrices , along with a collection of mathematical functions to operate on these data structures.\nIn thos lesson, we will cover the basics of Numpy , focusing on arrays and vectorized operations.'

In [4]:
import numpy as np
#1D array
arr1 = np.array([1,2,3,4,5])

In [5]:
print(type(arr1))
print(arr1.shape) # (5,) if left is blank then it is one dimension

<class 'numpy.ndarray'>
(5,)


In [6]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr3=np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [8]:
#2D Array
arr4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr4.shape

(2, 5)

In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
## Attributes of numpy
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements): ",arr.size)
print("Data type : ",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements):  6
Data type :  int64
Item size (in bytes): 8


In [13]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("addition : ",arr1+arr2)

## Element wise substraction
print("substraction : ",arr1-arr2)

addition :  [11 22 33 44 55]
substraction :  [ -9 -18 -27 -36 -45]


In [14]:
print(arr1 * arr1)

[ 1  4  9 16 25]


In [15]:
print(np.exp(arr1))
print(np.sin(arr1))
print(np.sqrt(arr1))
print(np.log(arr1))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [16]:
## Array slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array : \n",arr)

array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr[0][0]

np.int64(1)

In [18]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [20]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [21]:
arr[0,0] =  0
arr

array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr[1:] = 100
arr

array([[  0,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [23]:
### Statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalized the data
normalized_data = (data - mean) / std_dev
print("Normalized data: ",normalized_data)

#Output:
#Normalized data : [-1.26491106 -0.63245553 0. 0.63245553 1.26491106]

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [24]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean:",mean)

# Median
median = np.median(data)
print("Median:",median)

#Standard deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

# Variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [29]:
## Logical Operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5
data[data > 5]

array([ 6,  7,  8,  9, 10])

In [30]:
data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])